### ISSUE TITLE
Engine sounds

### ISSUE THREAD

**Issue by GooSee2001** [mrdivdiz/bpvita#4]
Engine sounds are always playing. Even in create mode and when they’re stopped.

**Comment by mrdivdiz** [comment]
Yeah, I know about that, since this game can handle only 1 CPU core by itself (originally developed in 2011 or something for mobile devices of that age), and single thread perfomance of ps vita is very, very bad, always playing engine sound is some kind of quickfix.And another problem is broken original prefab source code.May be improved, may not - no guarantee for that.

**Comment by GooSee2001** [comment]
Ok thanks.

**Comment by mrdivdiz** [comment]
I`ll try to improve sound system, but can`t promise anything.

**Comment by GooSee2001** [comment]
Ok. Better than nothing
